### PR TITLE
The Editing branch of my fork is now ready to be reviewed

### PR DESCRIPTION
**Pull request by DavidHaslam**
Consolidating 12 commits that fixed various issues in cross-references as well as updating the copyright date range and TBS address in the header files.

### CODE REVIEW

**Comment by teusbenschop** [comment]
Thanks a lot, David, for these fixes, all of them!

**Comment by DavidHaslam** [comment]
My pleasure.

**Comment by teusbenschop** [comment]
The team will be seeing and reviewing the changes tomorrow, after the nightly procedures has organized them into text-only changes.

**Comment by teusbenschop** [comment]
Everything has been reviewed, and it's 100% OK. (Just one double space to be changed to a single space, but that's nothing when compared to the magnitude of the amount of changes done through your filter) - Thanks!

**Pull request merged**
